import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { Router } from '@angular/router';
import { AuthenticationService } from 'src/app/services/authentication-service.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  error:string;
  registerForm: FormGroup;
  endpoint: string = 'http://localhost:4200/';
  constructor(
    public fb: FormBuilder,
    public authenticationService: AuthenticationService,
    public router: Router
  ) {
    this.registerForm = this.fb.group({
      email: [''],
      password: [''],
      screenName: ['']
    })
  }

  ngOnInit() {}
  
  registerUser() {
    //this.createNewUser(this.registerForm.value)
    this.registerForm.reset()
    this.router.navigate(['login']);
  }

  /*
   * This method allows the user to access in the app using JSON web token 
   * generated by node server.
   */
  /*
  createNewUser(user: UserComponent) {
    return this.authenticationService.getHttp().post<any>(`${this.endpoint}/login`, user)
      .subscribe((res: any) => {
        localStorage.setItem('access_token', res.token)
        this.authenticationService.getUserProfile(res._id).subscribe((res) => {
          this.authenticationService.currentUser = res;
          this.router.navigate(['login' + res.msg._id]);
        })
        alert("New User registered successfully.")
      })
  }
  */
}



  
  
