import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { Router } from '@angular/router';
import { AuthenticationService } from 'src/app/services/authentication-service.service';
import { User } from 'src/app/models/user';
import { UserService } from 'src/app/services/user.service';
import { UserComponent } from '../userComponent/user.component';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  userName: string;
  userEmail: string;
  userPassword: string;
  userPasswordRepeat: string;
  users: User[];

  // error:string;
  // registerForm: FormGroup;
  endpoint: string = 'http://localhost:8080/BreakingBad';
  constructor(
    public authenticationService: AuthenticationService,
    public router: Router,
    public userSer: UserService
  ) {
    // this.registerForm = this.fb.group({
    //   userEmail: [''],
    //   userPassword: [''],
    //   userName: ['']
    // })
  }
  // public fb: FormBuilder,
  
  ngOnInit() {}
  
  registerUser() {
    // this.createNewUser(this.registerForm.value)
    // this.registerForm.reset()
    this.router.navigate(['login']);
  }


  createNewUser() {
    let u = new User(0, this.userName, this.userEmail, this.userPassword, null, null)
    this.userSer.addUser(u).subscribe(
      (response: User[]) => {
        this.users = response;
      }
    )
  }

  /*
   * This method allows the user to access in the app using JSON web token 
   * generated by node server.
   */

  
  // createNewUser(user: UserComponent) {
  //   return this.authenticationService.getHttp().post<any>(`${this.endpoint}/login`, user)
  //     .subscribe((res: any) => {
  //       localStorage.setItem('access_token', res.token)
  //       this.authenticationService.getUserProfile(res._id).subscribe((res) => {
  //         this.authenticationService.currentUser = res;
  //         this.router.navigate(['login' + res.msg._id]);
  //       })
  //       alert("New User registered successfully.")
  //     })
  // }
  
}



  
  
